# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Setup.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(656, 474)
        Dialog.setAutoFillBackground(False)
        self.toolBox = QtGui.QToolBox(Dialog)
        self.toolBox.setGeometry(QtCore.QRect(20, 30, 471, 431))
        self.toolBox.setAutoFillBackground(False)
        self.toolBox.setObjectName(_fromUtf8("toolBox"))
        self.page_3 = QtGui.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 471, 193))
        self.page_3.setObjectName(_fromUtf8("page_3"))
        self.label_8 = QtGui.QLabel(self.page_3)
        self.label_8.setGeometry(QtCore.QRect(10, 0, 141, 21))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.doubleSpinBox = QtGui.QDoubleSpinBox(self.page_3)
        self.doubleSpinBox.setGeometry(QtCore.QRect(160, 0, 111, 22))
        self.doubleSpinBox.setProperty("value", 22.0)
        self.doubleSpinBox.setObjectName(_fromUtf8("doubleSpinBox"))
        self.label_9 = QtGui.QLabel(self.page_3)
        self.label_9.setGeometry(QtCore.QRect(290, 0, 31, 21))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.toolBox.addItem(self.page_3, _fromUtf8(""))
        self.page_5 = QtGui.QWidget()
        self.page_5.setGeometry(QtCore.QRect(0, 0, 471, 193))
        self.page_5.setObjectName(_fromUtf8("page_5"))
        self.doubleSpinBox_2 = QtGui.QDoubleSpinBox(self.page_5)
        self.doubleSpinBox_2.setGeometry(QtCore.QRect(160, 30, 111, 22))
        self.doubleSpinBox_2.setProperty("value", 22.0)
        self.doubleSpinBox_2.setObjectName(_fromUtf8("doubleSpinBox_2"))
        self.label_10 = QtGui.QLabel(self.page_5)
        self.label_10.setGeometry(QtCore.QRect(10, 0, 141, 21))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(self.page_5)
        self.label_11.setGeometry(QtCore.QRect(290, 30, 31, 21))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_27 = QtGui.QLabel(self.page_5)
        self.label_27.setGeometry(QtCore.QRect(10, 30, 141, 21))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.timeEdit_8 = QtGui.QTimeEdit(self.page_5)
        self.timeEdit_8.setGeometry(QtCore.QRect(160, 0, 111, 22))
        self.timeEdit_8.setObjectName(_fromUtf8("timeEdit_8"))
        self.label_24 = QtGui.QLabel(self.page_5)
        self.label_24.setGeometry(QtCore.QRect(290, 60, 31, 21))
        self.label_24.setText(_fromUtf8(""))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.label_28 = QtGui.QLabel(self.page_5)
        self.label_28.setGeometry(QtCore.QRect(10, 60, 141, 21))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.doubleSpinBox_8 = QtGui.QDoubleSpinBox(self.page_5)
        self.doubleSpinBox_8.setGeometry(QtCore.QRect(160, 60, 111, 22))
        self.doubleSpinBox_8.setProperty("value", 3.0)
        self.doubleSpinBox_8.setObjectName(_fromUtf8("doubleSpinBox_8"))
        self.toolBox.addItem(self.page_5, _fromUtf8(""))
        self.page_6 = QtGui.QWidget()
        self.page_6.setGeometry(QtCore.QRect(0, 0, 471, 193))
        self.page_6.setObjectName(_fromUtf8("page_6"))
        self.doubleSpinBox_3 = QtGui.QDoubleSpinBox(self.page_6)
        self.doubleSpinBox_3.setGeometry(QtCore.QRect(160, 0, 111, 22))
        self.doubleSpinBox_3.setProperty("value", 22.0)
        self.doubleSpinBox_3.setObjectName(_fromUtf8("doubleSpinBox_3"))
        self.label_13 = QtGui.QLabel(self.page_6)
        self.label_13.setGeometry(QtCore.QRect(290, 0, 31, 21))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_30 = QtGui.QLabel(self.page_6)
        self.label_30.setGeometry(QtCore.QRect(10, 0, 141, 21))
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.toolBox.addItem(self.page_6, _fromUtf8(""))
        self.page_7 = QtGui.QWidget()
        self.page_7.setGeometry(QtCore.QRect(0, 0, 471, 193))
        self.page_7.setObjectName(_fromUtf8("page_7"))
        self.doubleSpinBox_4 = QtGui.QDoubleSpinBox(self.page_7)
        self.doubleSpinBox_4.setGeometry(QtCore.QRect(160, 30, 111, 22))
        self.doubleSpinBox_4.setProperty("value", 22.0)
        self.doubleSpinBox_4.setObjectName(_fromUtf8("doubleSpinBox_4"))
        self.label_34 = QtGui.QLabel(self.page_7)
        self.label_34.setGeometry(QtCore.QRect(10, 60, 141, 21))
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.timeEdit_10 = QtGui.QTimeEdit(self.page_7)
        self.timeEdit_10.setGeometry(QtCore.QRect(160, 0, 111, 22))
        self.timeEdit_10.setObjectName(_fromUtf8("timeEdit_10"))
        self.label_15 = QtGui.QLabel(self.page_7)
        self.label_15.setGeometry(QtCore.QRect(290, 30, 31, 21))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_33 = QtGui.QLabel(self.page_7)
        self.label_33.setGeometry(QtCore.QRect(10, 30, 141, 21))
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.label_14 = QtGui.QLabel(self.page_7)
        self.label_14.setGeometry(QtCore.QRect(10, 0, 141, 21))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.doubleSpinBox_11 = QtGui.QDoubleSpinBox(self.page_7)
        self.doubleSpinBox_11.setGeometry(QtCore.QRect(160, 60, 111, 22))
        self.doubleSpinBox_11.setProperty("value", 5.0)
        self.doubleSpinBox_11.setObjectName(_fromUtf8("doubleSpinBox_11"))
        self.label_32 = QtGui.QLabel(self.page_7)
        self.label_32.setGeometry(QtCore.QRect(290, 60, 31, 21))
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.doubleSpinBox_16 = QtGui.QDoubleSpinBox(self.page_7)
        self.doubleSpinBox_16.setGeometry(QtCore.QRect(160, 90, 111, 22))
        self.doubleSpinBox_16.setProperty("value", 3.0)
        self.doubleSpinBox_16.setObjectName(_fromUtf8("doubleSpinBox_16"))
        self.label_45 = QtGui.QLabel(self.page_7)
        self.label_45.setGeometry(QtCore.QRect(10, 90, 141, 21))
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.label_46 = QtGui.QLabel(self.page_7)
        self.label_46.setGeometry(QtCore.QRect(10, 120, 141, 21))
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.doubleSpinBox_17 = QtGui.QDoubleSpinBox(self.page_7)
        self.doubleSpinBox_17.setGeometry(QtCore.QRect(160, 120, 111, 22))
        self.doubleSpinBox_17.setMaximum(10000.0)
        self.doubleSpinBox_17.setProperty("value", 1037.0)
        self.doubleSpinBox_17.setObjectName(_fromUtf8("doubleSpinBox_17"))
        self.label_44 = QtGui.QLabel(self.page_7)
        self.label_44.setGeometry(QtCore.QRect(290, 120, 41, 21))
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.toolBox.addItem(self.page_7, _fromUtf8(""))
        self.page_4 = QtGui.QWidget()
        self.page_4.setGeometry(QtCore.QRect(0, 0, 471, 193))
        self.page_4.setObjectName(_fromUtf8("page_4"))
        self.doubleSpinBox_5 = QtGui.QDoubleSpinBox(self.page_4)
        self.doubleSpinBox_5.setGeometry(QtCore.QRect(160, 30, 111, 22))
        self.doubleSpinBox_5.setProperty("value", 22.0)
        self.doubleSpinBox_5.setObjectName(_fromUtf8("doubleSpinBox_5"))
        self.label_16 = QtGui.QLabel(self.page_4)
        self.label_16.setGeometry(QtCore.QRect(10, 0, 141, 21))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.label_36 = QtGui.QLabel(self.page_4)
        self.label_36.setGeometry(QtCore.QRect(10, 30, 141, 21))
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.timeEdit_11 = QtGui.QTimeEdit(self.page_4)
        self.timeEdit_11.setGeometry(QtCore.QRect(160, 0, 111, 22))
        self.timeEdit_11.setObjectName(_fromUtf8("timeEdit_11"))
        self.label_17 = QtGui.QLabel(self.page_4)
        self.label_17.setGeometry(QtCore.QRect(290, 30, 31, 21))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.toolBox.addItem(self.page_4, _fromUtf8(""))
        self.page = QtGui.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 471, 193))
        self.page.setObjectName(_fromUtf8("page"))
        self.doubleSpinBox_6 = QtGui.QDoubleSpinBox(self.page)
        self.doubleSpinBox_6.setGeometry(QtCore.QRect(160, 30, 111, 22))
        self.doubleSpinBox_6.setProperty("value", 22.0)
        self.doubleSpinBox_6.setObjectName(_fromUtf8("doubleSpinBox_6"))
        self.doubleSpinBox_13 = QtGui.QDoubleSpinBox(self.page)
        self.doubleSpinBox_13.setGeometry(QtCore.QRect(160, 60, 111, 22))
        self.doubleSpinBox_13.setProperty("value", 5.0)
        self.doubleSpinBox_13.setObjectName(_fromUtf8("doubleSpinBox_13"))
        self.timeEdit_12 = QtGui.QTimeEdit(self.page)
        self.timeEdit_12.setGeometry(QtCore.QRect(160, 0, 111, 22))
        self.timeEdit_12.setObjectName(_fromUtf8("timeEdit_12"))
        self.label_40 = QtGui.QLabel(self.page)
        self.label_40.setGeometry(QtCore.QRect(10, 60, 141, 21))
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.label_18 = QtGui.QLabel(self.page)
        self.label_18.setGeometry(QtCore.QRect(10, 0, 141, 21))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.label_39 = QtGui.QLabel(self.page)
        self.label_39.setGeometry(QtCore.QRect(10, 30, 141, 21))
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.label_19 = QtGui.QLabel(self.page)
        self.label_19.setGeometry(QtCore.QRect(290, 30, 31, 21))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.label_38 = QtGui.QLabel(self.page)
        self.label_38.setGeometry(QtCore.QRect(290, 60, 31, 21))
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.toolBox.addItem(self.page, _fromUtf8(""))
        self.page_2 = QtGui.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 471, 193))
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.doubleSpinBox_7 = QtGui.QDoubleSpinBox(self.page_2)
        self.doubleSpinBox_7.setGeometry(QtCore.QRect(160, 0, 111, 22))
        self.doubleSpinBox_7.setProperty("value", 22.0)
        self.doubleSpinBox_7.setObjectName(_fromUtf8("doubleSpinBox_7"))
        self.label_42 = QtGui.QLabel(self.page_2)
        self.label_42.setGeometry(QtCore.QRect(10, 0, 141, 21))
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.label_21 = QtGui.QLabel(self.page_2)
        self.label_21.setGeometry(QtCore.QRect(290, 0, 31, 21))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.toolBox.addItem(self.page_2, _fromUtf8(""))
        self.comboBox = QtGui.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(500, 110, 151, 30))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.label_22 = QtGui.QLabel(Dialog)
        self.label_22.setGeometry(QtCore.QRect(500, 90, 71, 20))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.lineEdit = QtGui.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(502, 181, 151, 31))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.label_23 = QtGui.QLabel(Dialog)
        self.label_23.setGeometry(QtCore.QRect(500, 160, 141, 20))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.pushButton = QtGui.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(560, 220, 91, 28))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.lineEdit_2 = QtGui.QLineEdit(Dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(510, 390, 111, 31))
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.pushButton_2 = QtGui.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(560, 427, 91, 41))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.label = QtGui.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(631, 390, 61, 31))
        self.label.setObjectName(_fromUtf8("label"))

        self.retranslateUi(Dialog)
        self.toolBox.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "SetUp", None))
        self.label_8.setText(_translate("Dialog", "Stage Temperature", None))
        self.label_9.setText(_translate("Dialog", "ºC", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), _translate("Dialog", "Stage 1 <Base Heating>", None))
        self.label_10.setText(_translate("Dialog", "Stage Duration", None))
        self.label_11.setText(_translate("Dialog", "ºC", None))
        self.label_27.setText(_translate("Dialog", "Stage Temperature", None))
        self.label_28.setText(_translate("Dialog", "Malt Amount", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_5), _translate("Dialog", "Stage 2 <Malt Infusion>", None))
        self.label_13.setText(_translate("Dialog", "ºC", None))
        self.label_30.setText(_translate("Dialog", "Stage Temperature", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_6), _translate("Dialog", "Stage 3 <Must Filtering>", None))
        self.label_34.setText(_translate("Dialog", "Stage Pressure", None))
        self.label_15.setText(_translate("Dialog", "ºC", None))
        self.label_33.setText(_translate("Dialog", "Stage Temperature", None))
        self.label_14.setText(_translate("Dialog", "Stage Duration", None))
        self.label_32.setText(_translate("Dialog", "psi", None))
        self.label_45.setText(_translate("Dialog", "Hop Interval", None))
        self.label_46.setText(_translate("Dialog", "Density", None))
        self.label_44.setText(_translate("Dialog", "Kg/m³", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_7), _translate("Dialog", "Stage 4 <Must Boiling>", None))
        self.label_16.setText(_translate("Dialog", "Stage Duration", None))
        self.label_36.setText(_translate("Dialog", "Stage Temperature", None))
        self.label_17.setText(_translate("Dialog", "ºC", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_4), _translate("Dialog", "Stage 5 <Yeast Add>", None))
        self.label_40.setText(_translate("Dialog", "Stage Pressure", None))
        self.label_18.setText(_translate("Dialog", "Stage Duration", None))
        self.label_39.setText(_translate("Dialog", "Stage Temperature", None))
        self.label_19.setText(_translate("Dialog", "ºC", None))
        self.label_38.setText(_translate("Dialog", "psi", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("Dialog", "Stage 6 <Fermentation>", None))
        self.label_42.setText(_translate("Dialog", "Stage Temperature", None))
        self.label_21.setText(_translate("Dialog", "ºC", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("Dialog", "Stage 7 <Beer Out>", None))
        self.comboBox.setItemText(0, _translate("Dialog", "Lagger", None))
        self.comboBox.setItemText(1, _translate("Dialog", "IPA", None))
        self.comboBox.setItemText(2, _translate("Dialog", "Stout", None))
        self.label_22.setText(_translate("Dialog", "Preconfig", None))
        self.lineEdit.setText(_translate("Dialog", "new_type", None))
        self.label_23.setText(_translate("Dialog", "Save as", None))
        self.pushButton.setText(_translate("Dialog", "Save", None))
        self.lineEdit_2.setText(_translate("Dialog", "20", None))
        self.pushButton_2.setText(_translate("Dialog", "Start", None))
        self.label.setText(_translate("Dialog", "Lts", None))

